
package store;
import javax.swing.*;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Venta");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCerrarSesion = new javax.swing.JButton();
        btCleanVenta = new javax.swing.JButton();
        btPagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ivProducto4 = new javax.swing.JLabel();
        tPizza = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JLabel();
        tSalchipapa = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JLabel();
        tHamburguer = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();
        tCola = new javax.swing.JLabel();
        precio4 = new javax.swing.JLabel();
        txtCantidad5 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JLabel();
        MiTiendita = new javax.swing.JLabel();
        etCantidad1 = new javax.swing.JTextField();
        btResta1 = new javax.swing.JButton();
        btSuma1 = new javax.swing.JButton();
        etCantidad2 = new javax.swing.JTextField();
        btResta2 = new javax.swing.JButton();
        btSuma2 = new javax.swing.JButton();
        btResta3 = new javax.swing.JButton();
        etCantidad3 = new javax.swing.JTextField();
        btSuma3 = new javax.swing.JButton();
        btResta4 = new javax.swing.JButton();
        etCantidad4 = new javax.swing.JTextField();
        btSuma4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tSuizo = new javax.swing.JLabel();
        precio5 = new javax.swing.JLabel();
        txtCantidad4 = new javax.swing.JLabel();
        btSuma5 = new javax.swing.JButton();
        etCantidad5 = new javax.swing.JTextField();
        btResta5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tAceiteVegetal1 = new javax.swing.JLabel();
        precio6 = new javax.swing.JLabel();
        btSuma6 = new javax.swing.JButton();
        txtCantidad3 = new javax.swing.JLabel();
        etCantidad6 = new javax.swing.JTextField();
        btResta6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tTacos = new javax.swing.JLabel();
        precio7 = new javax.swing.JLabel();
        txtCantidad6 = new javax.swing.JLabel();
        btSuma7 = new javax.swing.JButton();
        etCantidad7 = new javax.swing.JTextField();
        btResta7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tCubano = new javax.swing.JLabel();
        precio8 = new javax.swing.JLabel();
        txtCantidad7 = new javax.swing.JLabel();
        btSuma8 = new javax.swing.JButton();
        etCantidad8 = new javax.swing.JTextField();
        btResta8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tPapas = new javax.swing.JLabel();
        precio9 = new javax.swing.JLabel();
        txtCantidad8 = new javax.swing.JLabel();
        btSuma9 = new javax.swing.JButton();
        etCantidad9 = new javax.swing.JTextField();
        btResta9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tPapas1 = new javax.swing.JLabel();
        precio10 = new javax.swing.JLabel();
        txtCantidad9 = new javax.swing.JLabel();
        btSuma10 = new javax.swing.JButton();
        etCantidad10 = new javax.swing.JTextField();
        btResta10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCerrarSesion.setText("Cerrar sesión");
        btCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 170, 51));

        btCleanVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCleanVenta.setText("Cancelar compra");
        btCleanVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCleanVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btCleanVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 170, 51));

        btPagar.setBackground(new java.awt.Color(255, 255, 0));
        btPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btPagar.setText("Proceder al pago");
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 170, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/perro.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/salchipapa.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/Hamburguesa.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        ivProducto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/refresco.jpg"))); // NOI18N
        jPanel1.add(ivProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 170, -1));

        tPizza.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tPizza.setForeground(new java.awt.Color(255, 255, 255));
        tPizza.setText("Pizza");
        jPanel1.add(tPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        precio1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio1.setForeground(new java.awt.Color(255, 255, 0));
        precio1.setText("$12.000");
        jPanel1.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setText("Cantidad");
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        tSalchipapa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tSalchipapa.setForeground(new java.awt.Color(255, 255, 255));
        tSalchipapa.setText("Salchipapa");
        jPanel1.add(tSalchipapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        precio2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio2.setForeground(new java.awt.Color(255, 255, 0));
        precio2.setText("$10.000");
        jPanel1.add(precio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        txtCantidad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad1.setText("Cantidad");
        jPanel1.add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        tHamburguer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tHamburguer.setForeground(new java.awt.Color(255, 255, 255));
        tHamburguer.setText("Combo burguer");
        jPanel1.add(tHamburguer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        precio3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio3.setForeground(new java.awt.Color(255, 255, 0));
        precio3.setText("$22.500");
        jPanel1.add(precio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        tCola.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tCola.setForeground(new java.awt.Color(255, 255, 255));
        tCola.setText("Refresco en lata");
        jPanel1.add(tCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        precio4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio4.setForeground(new java.awt.Color(255, 255, 0));
        precio4.setText("$6.000");
        jPanel1.add(precio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        txtCantidad5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad5.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad5.setText("Cantidad");
        jPanel1.add(txtCantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        txtCantidad2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad2.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad2.setText("Cantidad");
        jPanel1.add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        MiTiendita.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        MiTiendita.setForeground(new java.awt.Color(255, 255, 51));
        MiTiendita.setText("MI TIENDITA");
        jPanel1.add(MiTiendita, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        etCantidad1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad1.setText("0");
        etCantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad1ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 50, 30));

        btResta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta1.setText("-");
        btResta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta1ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 50, 30));

        btSuma1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma1.setText("+");
        btSuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma1ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 50, 30));

        etCantidad2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad2.setText("0");
        jPanel1.add(etCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 50, 30));

        btResta2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta2.setText("-");
        btResta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta2ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 50, 30));

        btSuma2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma2.setText("+");
        btSuma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma2ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 50, 30));

        btResta3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta3.setText("-");
        btResta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta3ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 50, 30));

        etCantidad3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad3.setText("0");
        jPanel1.add(etCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 50, 30));

        btSuma3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma3.setText("+");
        btSuma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma3ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 50, 30));

        btResta4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta4.setText("-");
        btResta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta4ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 50, 30));

        etCantidad4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad4.setText("0");
        etCantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad4ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 50, 30));

        btSuma4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma4.setText("+");
        btSuma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma4ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 50, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/suizoo.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 69, 220, 170));

        tSuizo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tSuizo.setForeground(new java.awt.Color(255, 255, 255));
        tSuizo.setText("Suizo especial");
        jPanel1.add(tSuizo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, -1));

        precio5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio5.setForeground(new java.awt.Color(255, 255, 102));
        precio5.setText("$15.000");
        jPanel1.add(precio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, -1, -1));

        txtCantidad4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad4.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad4.setText("Cantidad");
        jPanel1.add(txtCantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, -1, -1));

        btSuma5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma5.setText("+");
        btSuma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma5ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 50, 30));

        etCantidad5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad5.setText("0");
        etCantidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad5ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, 50, 30));

        btResta5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta5.setText("-");
        btResta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta5ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/pizzaa.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 180, 130));

        tAceiteVegetal1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tAceiteVegetal1.setForeground(new java.awt.Color(255, 255, 255));
        tAceiteVegetal1.setText("Perro caliente");
        jPanel1.add(tAceiteVegetal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        precio6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio6.setForeground(new java.awt.Color(255, 255, 0));
        precio6.setText("$4.000");
        jPanel1.add(precio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        btSuma6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma6.setText("+");
        btSuma6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma6ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 50, 30));

        txtCantidad3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad3.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad3.setText("Cantidad");
        jPanel1.add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        etCantidad6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad6.setText("0");
        etCantidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad6ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 50, 30));

        btResta6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta6.setText("-");
        btResta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta6ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 50, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/tacos-mexicanos (1).jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 180, 130));

        tTacos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tTacos.setForeground(new java.awt.Color(255, 255, 255));
        tTacos.setText("Tacos");
        jPanel1.add(tTacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        precio7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio7.setForeground(new java.awt.Color(255, 255, 0));
        precio7.setText("$7.000");
        jPanel1.add(precio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        txtCantidad6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad6.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad6.setText("Cantidad");
        jPanel1.add(txtCantidad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        btSuma7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma7.setText("+");
        btSuma7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma7ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 50, 30));

        etCantidad7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad7.setText("0");
        etCantidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad7ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 50, 30));

        btResta7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta7.setText("-");
        btResta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta7ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 50, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/sancubano.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 180, 130));

        tCubano.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tCubano.setForeground(new java.awt.Color(255, 255, 255));
        tCubano.setText("Sanduche Cubano");
        jPanel1.add(tCubano, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        precio8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio8.setForeground(new java.awt.Color(255, 255, 0));
        precio8.setText("$11.000");
        jPanel1.add(precio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        txtCantidad7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad7.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad7.setText("Cantidad");
        jPanel1.add(txtCantidad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));

        btSuma8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma8.setText("+");
        btSuma8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma8ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 50, 30));

        etCantidad8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad8.setText("0");
        etCantidad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad8ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 50, 30));

        btResta8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta8.setText("-");
        btResta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta8ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 50, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/papitas.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 190, 130));

        tPapas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tPapas.setForeground(new java.awt.Color(255, 255, 255));
        tPapas.setText("Papas fritas en salsa");
        jPanel1.add(tPapas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        precio9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio9.setForeground(new java.awt.Color(255, 255, 0));
        precio9.setText("$3.500");
        jPanel1.add(precio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        txtCantidad8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad8.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad8.setText("Cantidad");
        jPanel1.add(txtCantidad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, -1, -1));

        btSuma9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma9.setText("+");
        btSuma9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma9ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 50, 30));

        etCantidad9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad9.setText("0");
        etCantidad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad9ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 50, 30));

        btResta9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta9.setText("-");
        btResta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta9ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 50, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/arepa.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, -1, -1));

        tPapas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tPapas1.setForeground(new java.awt.Color(255, 255, 255));
        tPapas1.setText("Arepa rellena");
        jPanel1.add(tPapas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, -1, -1));

        precio10.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        precio10.setForeground(new java.awt.Color(255, 255, 0));
        precio10.setText("$9.000");
        jPanel1.add(precio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, -1, -1));

        txtCantidad9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad9.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad9.setText("Cantidad");
        jPanel1.add(txtCantidad9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, -1, -1));

        btSuma10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSuma10.setText("+");
        btSuma10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuma10ActionPerformed(evt);
            }
        });
        jPanel1.add(btSuma10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, 50, 30));

        etCantidad10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etCantidad10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etCantidad10.setText("0");
        etCantidad10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etCantidad10ActionPerformed(evt);
            }
        });
        jPanel1.add(etCantidad10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 50, 30));

        btResta10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResta10.setText("-");
        btResta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResta10ActionPerformed(evt);
            }
        });
        jPanel1.add(btResta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btResta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta1ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad1.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad1.setText(resultado);
    }//GEN-LAST:event_btResta1ActionPerformed

    private void btResta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta2ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad2.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad2.setText(resultado);
    }//GEN-LAST:event_btResta2ActionPerformed

    private void btResta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta3ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad3.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad3.setText(resultado);
    }//GEN-LAST:event_btResta3ActionPerformed

    private void btResta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta4ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad4.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad4.setText(resultado);
    }//GEN-LAST:event_btResta4ActionPerformed

    private void btSuma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma2ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad2.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad2.setText(resultado);
    }//GEN-LAST:event_btSuma2ActionPerformed

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        // TODO add your handling code here:
        
        String cantidad1= etCantidad1.getText();
        int c1 = Integer.parseInt(cantidad1);
        String cantidad2= etCantidad2.getText();
        int c2 = Integer.parseInt(cantidad2);
        String cantidad3= etCantidad3.getText();
        int c3 = Integer.parseInt(cantidad3);
        String cantidad4= etCantidad4.getText();
        int c4 = Integer.parseInt(cantidad4);
        String cantidad5= etCantidad5.getText();
        int c5 = Integer.parseInt(cantidad5);
        String cantidad6= etCantidad6.getText();
        int c6 = Integer.parseInt(cantidad6);
        String cantidad7= etCantidad7.getText();
        int c7 = Integer.parseInt(cantidad7);
        String cantidad8= etCantidad8.getText();
        int c8 = Integer.parseInt(cantidad8);
        String cantidad9= etCantidad9.getText();
        int c9 = Integer.parseInt(cantidad9);
        String cantidad10= etCantidad10.getText();
        int c10 = Integer.parseInt(cantidad10);
        
        if(c1==0 && c2==0 && c3==0 && c4==0 && c5==0 && c6==0 && c7==0 && c8==0 && c9==0 && c10==0){
            JOptionPane.showMessageDialog(null, "No hay articulos para pagar");
        }else{
            if(c1<0|| c2<0 || c3<0  || c4<0 || c5<0 || c6<0 || c7<0 || c8<0 || c9<0 || c10<0){
            JOptionPane.showMessageDialog(null, "NO PUEDES INGRESAR CANTIDADES NEGATIVAS");
            }else{
                this.setVisible(false);
                VentanaDescripcion ventana3 = new VentanaDescripcion();
        
                ventana3.cantidades(cantidad1, cantidad2, cantidad3, cantidad4, cantidad5,  cantidad6, cantidad7, cantidad8, cantidad9, cantidad10);
                ventana3.setVisible(true);
            }
        }  
    }//GEN-LAST:event_btPagarActionPerformed
    
    private void btSuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma1ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad1.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad1.setText(resultado);
    }//GEN-LAST:event_btSuma1ActionPerformed

    private void btSuma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma3ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad3.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad3.setText(resultado);
    }//GEN-LAST:event_btSuma3ActionPerformed

    private void btSuma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma4ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad4.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad4.setText(resultado);
    }//GEN-LAST:event_btSuma4ActionPerformed

    private void etCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad1ActionPerformed

    
    private void btCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarSesionActionPerformed
        // TODO add your handling code here:
        Login ventana1 = new Login();
        this.setVisible(false);
    }//GEN-LAST:event_btCerrarSesionActionPerformed

    private void btCleanVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCleanVentaActionPerformed
        // TODO add your handling code here:
        etCantidad1.setText("0");
        etCantidad2.setText("0");
        etCantidad3.setText("0");
        etCantidad4.setText("0");
        etCantidad5.setText("0");
        etCantidad6.setText("0");
        etCantidad7.setText("0");
        etCantidad8.setText("0");
        etCantidad9.setText("0");
        etCantidad10.setText("0");
    }//GEN-LAST:event_btCleanVentaActionPerformed

    private void btSuma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma5ActionPerformed
        // TODO add your handling code here:
         Integer cantidad = Integer.parseInt(etCantidad5.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad5.setText(resultado);
    }//GEN-LAST:event_btSuma5ActionPerformed

    private void btResta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta5ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad5.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad5.setText(resultado);
    }//GEN-LAST:event_btResta5ActionPerformed

    private void etCantidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad5ActionPerformed

    private void etCantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad4ActionPerformed

    private void btSuma6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma6ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad6.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad6.setText(resultado);
    }//GEN-LAST:event_btSuma6ActionPerformed

    private void etCantidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad6ActionPerformed

    private void btResta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta6ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad6.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad6.setText(resultado);
    }//GEN-LAST:event_btResta6ActionPerformed

    private void btSuma7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma7ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad7.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad7.setText(resultado);
    }//GEN-LAST:event_btSuma7ActionPerformed

    private void etCantidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad7ActionPerformed

    private void btResta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta7ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad7.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad7.setText(resultado);
    }//GEN-LAST:event_btResta7ActionPerformed

    private void btSuma8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma8ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad8.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad8.setText(resultado);
    }//GEN-LAST:event_btSuma8ActionPerformed

    private void etCantidad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad8ActionPerformed

    private void btResta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta8ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad8.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad8.setText(resultado);
    }//GEN-LAST:event_btResta8ActionPerformed

    private void btSuma9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma9ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad9.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad9.setText(resultado);
    }//GEN-LAST:event_btSuma9ActionPerformed

    private void etCantidad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad9ActionPerformed

    private void btResta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta9ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad9.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad9.setText(resultado);
    }//GEN-LAST:event_btResta9ActionPerformed

    private void btSuma10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuma10ActionPerformed
        // TODO add your handling code here
        Integer cantidad = Integer.parseInt(etCantidad10.getText());
        
        String resultado = String.valueOf(suma(cantidad));
       
        etCantidad10.setText(resultado);
    }//GEN-LAST:event_btSuma10ActionPerformed

    private void etCantidad10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etCantidad10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etCantidad10ActionPerformed

    private void btResta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResta10ActionPerformed
        // TODO add your handling code here:
        Integer cantidad = Integer.parseInt(etCantidad10.getText());
        
        String resultado = String.valueOf(resta(cantidad));
       
        etCantidad10.setText(resultado);
    }//GEN-LAST:event_btResta10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    private int suma(int cantidad){
        cantidad = cantidad +1;        
        return cantidad;
    }
    private int resta(int cantidad){
        if(cantidad>0){
            cantidad = cantidad -1;
        }
        return cantidad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MiTiendita;
    private javax.swing.JButton btCerrarSesion;
    private javax.swing.JButton btCleanVenta;
    private javax.swing.JButton btPagar;
    private javax.swing.JButton btResta1;
    private javax.swing.JButton btResta10;
    private javax.swing.JButton btResta2;
    private javax.swing.JButton btResta3;
    private javax.swing.JButton btResta4;
    private javax.swing.JButton btResta5;
    private javax.swing.JButton btResta6;
    private javax.swing.JButton btResta7;
    private javax.swing.JButton btResta8;
    private javax.swing.JButton btResta9;
    private javax.swing.JButton btSuma1;
    private javax.swing.JButton btSuma10;
    private javax.swing.JButton btSuma2;
    private javax.swing.JButton btSuma3;
    private javax.swing.JButton btSuma4;
    private javax.swing.JButton btSuma5;
    private javax.swing.JButton btSuma6;
    private javax.swing.JButton btSuma7;
    private javax.swing.JButton btSuma8;
    private javax.swing.JButton btSuma9;
    private javax.swing.JTextField etCantidad1;
    private javax.swing.JTextField etCantidad10;
    private javax.swing.JTextField etCantidad2;
    private javax.swing.JTextField etCantidad3;
    private javax.swing.JTextField etCantidad4;
    private javax.swing.JTextField etCantidad5;
    private javax.swing.JTextField etCantidad6;
    private javax.swing.JTextField etCantidad7;
    private javax.swing.JTextField etCantidad8;
    private javax.swing.JTextField etCantidad9;
    private javax.swing.JLabel ivProducto4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio10;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JLabel precio4;
    private javax.swing.JLabel precio5;
    private javax.swing.JLabel precio6;
    private javax.swing.JLabel precio7;
    private javax.swing.JLabel precio8;
    private javax.swing.JLabel precio9;
    private javax.swing.JLabel tAceiteVegetal1;
    private javax.swing.JLabel tCola;
    private javax.swing.JLabel tCubano;
    private javax.swing.JLabel tHamburguer;
    private javax.swing.JLabel tPapas;
    private javax.swing.JLabel tPapas1;
    private javax.swing.JLabel tPizza;
    private javax.swing.JLabel tSalchipapa;
    private javax.swing.JLabel tSuizo;
    private javax.swing.JLabel tTacos;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtCantidad1;
    private javax.swing.JLabel txtCantidad2;
    private javax.swing.JLabel txtCantidad3;
    private javax.swing.JLabel txtCantidad4;
    private javax.swing.JLabel txtCantidad5;
    private javax.swing.JLabel txtCantidad6;
    private javax.swing.JLabel txtCantidad7;
    private javax.swing.JLabel txtCantidad8;
    private javax.swing.JLabel txtCantidad9;
    // End of variables declaration//GEN-END:variables
}
